### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by IBims1CoolesTim** [runi95/turtle-control-panel#1]
How to startup the Web Interface?

**Comment by runi95** [comment]
Change your working directory to `portal` with `$ cd portal` and then run `$ npm i` to install all required dependencies followed by `$ npm start` to start the actual web interface. Mind you need to have NPM installed for this to work.

**Comment by IBims1CoolesTim** [comment]
now it says failed to connect

**Comment by IBims1CoolesTim** [comment]
![U2dasdnbenannt](https://user-images.githubusercontent.com/77571110/112485269-0b006080-8d7b-11eb-84c6-caad63e4f37f.PNG)

**Comment by runi95** [comment]
Yeah, the website needs a server to talk to so you'll also need to use Node to start up the API server. If your current working directory is the root of the project then you need to first install all the API's packages with `$ npm i` and then start the API with `$ node src`. The web page will the automatically reconnect to the server (after a given amount of time or a refresh). If you want to have any turtles on the control panel you'll still have to load the turtle script onto your turtles (and make sure you change the `local connectionURL = "<INPUT YOUR CONNECTION URL HERE>"` to whatever URL you'll use to connect your turtles to your API server).
