### ISSUE TITLE
Use svg icons instead of font glyphs

### ISSUE THREAD

**Issue by DarkReaper231** [runi95/turtle-control-panel#11]
![image](https://github.com/runi95/turtle-control-panel/assets/38611351/33d5230c-ca2b-4f12-bfbd-655cb6b27b7f)
On Linux this is a problem as most of the fonts Windows has are not present in Linux by default so relying on font glyphs is not a good idea. Or there also could be differences between distros.

**Comment by runi95** [comment]
Yeah, it's supposed to be the Unicode character `U+1F808` which renders fine on my Debian Bookworm laptop, but might not render on all Linux distros.
I agree that I should use proper icons like SVG files instead of Unicode characters and this really just comes down to me being lazy. 😅

**Comment by runi95** [comment]
Unicode character icons have been replaced with proper SVG icons.
