### ISSUE TITLE
serializeJSON expected boolean, got table

### ISSUE THREAD

**Issue by sn0wwfall** [runi95/turtle-control-panel#17]
Just setup the turtle and as I went to connect it I got this error, the second argument happens when I put in fuel
![image](https://github.com/runi95/turtle-control-panel/assets/72948990/c3a88a9c-36e8-43c7-89d3-3a1b0817a267)

**Comment by runi95** [comment]
@sn0wwfall looks like you might be running an older version of CC:Tweaked / Computercraft than I am. Do you happen to know which version you're running?

I'll also see if I can make this compatible with older versions of Computercraft, but I might have to draw the line somewhere, just don't quite know where yet.

**Comment by runi95** [comment]
I've fixed the issue with serializeJSON for older versions of ComputerCraft. Not sure if there are other issues for you since I'm not sure what version you're running, but this one should be fixed now.
