### ISSUE TITLE
Turtle Dosnt show up on the dashboard 

### ISSUE THREAD

**Issue by flexhd41** [runi95/turtle-control-panel#5]
The turtle itself says its connected but it dosnt show up could be because i changed the port of the backend but also changed the port in the app.tsx file 
![image](https://github.com/runi95/turtle-control-panel/assets/83534174/67fb5d99-81d9-462a-beeb-babc4ccb05f2)
![image](https://github.com/runi95/turtle-control-panel/assets/83534174/2d71265a-3506-429a-a231-e192f4fef384)

**Comment by runi95** [comment]
Not quite sure what's going on with your portal here, but as a sanity check does your server say the turtle has connected? It should look something like this when a turtle connects to the backend server:

```
[1] info        28-11-2023 06:29:39     Starting server...
[1] info        28-11-2023 06:29:39     Listening on port 6868
[1] info        28-11-2023 06:33:31     Incoming connection...
[1] info        28-11-2023 06:33:31     Initiating handshake...
[1] info        28-11-2023 06:33:32     Incoming connection...
[1] info        28-11-2023 06:33:32     Initiating handshake...
[1] info        28-11-2023 06:33:32     Sol [0] has connected!
[1] info        28-11-2023 06:33:33     Freia [18] has connected!
```

And then my portal let's me know they're connected:

![Screenshot 2023-11-28 at 18-35-07 TCP](https://github.com/runi95/turtle-control-panel/assets/4856656/2ba71e3d-65f7-434e-bf79-7b06d9b929de)

If I change the server port without updating the portal it currently looks like the following:

![Screenshot 2023-11-28 at 18-36-06 TCP](https://github.com/runi95/turtle-control-panel/assets/4856656/6b0d5ce1-df96-4d02-93eb-43693f98898b)

If you know how to you could open your browser's developer tools and check the network tab for WebSocket connections and then make sure it manages to establish a proper connection to your server.

**Comment by flexhd41** [comment]
the server dosnt mention anything 
![image](https://github.com/runi95/turtle-control-panel/assets/83534174/426d365a-fc4a-4ce7-8253-c849bde634d3)
for the network tab one gets the ip with 25569 that call is just called ws and another one with 25568 is called the domain name i use

**Comment by flexhd41** [comment]
also i saw this in the console 
![image](https://github.com/runi95/turtle-control-panel/assets/83534174/395d57c6-2bce-42f1-b3e4-8d9060fa22c6)

**Comment by runi95** [comment]
Oh-yeah, the issue is probably that there's a second WebSocket servers running from `server/src/entities/turtle.ts` that's supposed to handle the communication with the turtles.
I'm honestly not too sure why I've set it up like this, probably just because it was easier to separate the portal and the turtles then.

**Comment by runi95** [comment]
I've made some changes to make the second WebSocket server more obvious as well as added an environment variable `TURTLE_WSS_PORT` that allows you to configure the port for it.

**Comment by flexhd41** [comment]
Alright thank you for the help Really like this project it works now 
![image](https://github.com/runi95/turtle-control-panel/assets/83534174/f43117f4-8373-42d7-940c-1d168e5681eb)
