### ISSUE TITLE
Turtle reproduction

### ISSUE THREAD

**Issue by DarkReaper231** [runi95/turtle-control-panel#7]
Similar to turtle gambit, it would be nice if the turtles could reproduce so the user doesn't have to ever physically join the server

**Comment by runi95** [comment]
I don't really want to automate this task because it really doesn't seem that fun or useful to me, but I could make it possible to do this manually via the UI. Right now you can craft the turtle and place it using the build module so all you'd really need for this is to be able to interact with the new turtle so that you can create the startup script.

How does that sound?

**Comment by DarkReaper231** [comment]
Yeah! Controlling the turtles would be really nice. Idk if it's already possible to also move them manually or make them place signs but that would be a nice feature too. And when doing this manual control, a reproduction macro could also be added so user doesn't have to input manually all the steps.

**Comment by DarkReaper231** [comment]
Basically remote control for movement, breaking, placing and so on would also be nice. With the ability to put text on signs as well and a macro to reproduce.

**Comment by runi95** [comment]
This one should now be possible.
You'll need to have a `Chest` with a `Wired Modem` connected to it, this allows you to seamlessly move items between the chest and the turtle.

Steps:
  1. Gather the necessary materials to craft another turtle from the chest (hold down shift when dragging items to choose the amount).
  2. Either equip a `Crafting Table` or stand next to one to use the `Craft` peripheral action.
  3. Either use a pre-placed `Disk Drive` (easiest) or craft and place a `Disk Drive`.
  4. Place the newly crafted turtle adjacent to the `Disk Drive`.
  5. Gather the necessary materials to craft a `Floppy Disk`.
  6. Use the `Craft` peripheral action to craft a `Floppy Disk`.
  7. Make sure your turtle is facing the `Disk Drive` and drop the `Floppy Disk` into it.
  8. Use the drive peripheral to `Create file` and name the file `startup` (put the contents of `turtle/startup.lua` into this file).
  9. Move next to the turtle you placed down earlier.
  10. Use the turtle peripheral to `Reboot` the turtle.
  
Once you've done this one time you can skip most of this process by just leaving the `Floppy Disk` in the `Disk Drive`. Then all you need to do is place the new turtle next to the drive and reboot the turtle to create another one.

Note that you need to use the "Build" button to place down blocks.
