### ISSUE TITLE
Can't run the server

### ISSUE THREAD

**Issue by DarkReaper231** [runi95/turtle-control-panel#9]
After running `npm install` and `npm start`, it says this
```
node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module '/home/ruda0/Github/turtle-control-panel/server/dist/src/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Turns out it's trying to run `swc src -d dist` which should generate that folder but what the hell is dist? I don't have that.

EDIT: I installed swc and ran that command but this should probably be in README

**Comment by runi95** [comment]
Hm... honestly not quite sure what's going on here. `swc` is already a dependency under `devDependencies` with the name `@swc/cli` and should have been installed after you ran the `npm install` command previously. There might be some differences with our OS or NPM / Node setup which I haven't accounted for.

Did you have to install SWC separately to make this work for you?

I'll gladly update the script or the README if we can find out what's causing this.

**Comment by DarkReaper231** [comment]
@runi95 Actually `npm run dev` works perfectly. It's just `npm start` that doesn't work. For `npm start` I have to run `npx swc src -d dist` first

**Comment by runi95** [comment]
Oh-yeah, I see what the issue is now. In the README.md there's actually a slight different between running the server and running the portal. The server needs to run `npm run build` before `npm start` as stated.

**Comment by runi95** [comment]
Added a description on how to start the server in development mode to `README.md` in case someone else would like to run the server that way.

**Comment by DarkReaper231** [comment]
@runi95 Even with npm run build I am getting 
![image](https://github.com/runi95/turtle-control-panel/assets/38611351/4c79c4a2-f904-4aaf-9395-e8540a0b6dd7)
swc is not recognized as an executable
